# Generated by Django 4.0.5 on 2022-06-22 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 19, 20, 10, 478529, tzinfo=utc)),
        ),
    ]
