# Generated by Django 4.0.5 on 2022-06-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.CharField(choices=[('M', 'Must Watch'), ('S', 'Should Watch'), ('A', 'Avoid Watch'), ('NO', 'No Opinion')], default='NO', max_length=50),
        ),
    ]
