# Generated by Django 4.0.5 on 2022-06-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_user_review_critic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.CharField(choices=[('Must Watch', 'Must'), ('Should Watch', 'Should'), ('Avoid Watch', 'Avoid'), ('No Opinion', 'No')], default='No Opinion', max_length=50),
        ),
    ]
